vich_uploader:
    db_driver: orm
    
    mappings:
        product_videos:
            uri_prefix: '%app.path.product_videos%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_videos%'